# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scheduler_pb2 as scheduler__pb2


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.stream_stream(
                '/schedulerpb.SchedulerService/connect',
                request_serializer=scheduler__pb2.ClientRequest.SerializeToString,
                response_deserializer=scheduler__pb2.ClientResponse.FromString,
                )
        self.debug = channel.unary_unary(
                '/schedulerpb.SchedulerService/debug',
                request_serializer=scheduler__pb2.DebugRequest.SerializeToString,
                response_deserializer=scheduler__pb2.DebugResponse.FromString,
                )


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def debug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.stream_stream_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=scheduler__pb2.ClientRequest.FromString,
                    response_serializer=scheduler__pb2.ClientResponse.SerializeToString,
            ),
            'debug': grpc.unary_unary_rpc_method_handler(
                    servicer.debug,
                    request_deserializer=scheduler__pb2.DebugRequest.FromString,
                    response_serializer=scheduler__pb2.DebugResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedulerpb.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/schedulerpb.SchedulerService/connect',
            scheduler__pb2.ClientRequest.SerializeToString,
            scheduler__pb2.ClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def debug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/schedulerpb.SchedulerService/debug',
            scheduler__pb2.DebugRequest.SerializeToString,
            scheduler__pb2.DebugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
