# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x05image\"G\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x63\x61meraId\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\" \n\rImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x0cImageService\x12\x38\n\tSendImage\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=23
  _globals['_IMAGEREQUEST']._serialized_end=94
  _globals['_IMAGERESPONSE']._serialized_start=96
  _globals['_IMAGERESPONSE']._serialized_end=128
  _globals['_IMAGESERVICE']._serialized_start=130
  _globals['_IMAGESERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
